### ISSUE TITLE
不能配置成服务（.service）文件用systemctl管理

### ISSUE THREAD

**Issue by ZILCKIQ** [SeptemberHX/dde-globalmenu-service#4]
希望能够改进下程序，配置成.service文件用systemctl管理

**Comment by SeptemberHX** [comment]
之前尝试过，但是发现必须要等图形界面起来后才能够启动，不然会报错。后面再研究研究

**Comment by aykutkaraca** [comment]
What does that global menu repository do? Sorry for posting on issues page but it doest say in readme... :)

**Comment by SeptemberHX** [comment]
> What does that global menu repository do? Sorry for posting on issues page but it doest say in readme... :)

It provides necessary system dbus services to enable global menu feature for most gui applications. When running with dde-top-panel, the menus of applications will show on the top panel instead of in the application window.

**Comment by aykutkaraca** [comment]
> > What does that global menu repository do? Sorry for posting on issues page but it doest say in readme... :)
> 
> It provides necessary system dbus services to enable global menu feature for most gui applications. When running with dde-top-panel, the menus of applications will show on the top panel instead of in the application window.

Hey mate that totally solved my problem with DDE-Dock datetime plugin. It was using wrong dbus service probably and it was freezing so after installing your global menu service it doesnt freeze.

And it also solved the problems I mentioned in the top panel. So you must write in your readme that globalmenu service is a must. Otherwise my dde-dock was starting stopping before installing global menu. Thank you for support!
